[package]
name = "three"
version = "0.1.0"
authors = ["thekashifmalik <emailkashifmalik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
